Controllers/ShopManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TSENA.Models;

namespace TSENA.Controllers
{
    public class ShopManagementController : Controller
    {
        private readonly ShopManagementeContext _context;

        public ShopManagementController(ShopManagementeContext context)
        {
            _context = context;
        }

        // GET: ShopManagement
        public async Task<IActionResult> Index()
        {
            if(User.Identity?.IsAuthenticated ?? false){
                return View(await _context.Shop.ToListAsync());
            }else{
                return View();
            }
        }

        // GET: ShopManagement/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shop
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // GET: ShopManagement/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ShopManagement/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ShopName,ShopCreationDate,ShopLogoNetworkPath")] Shop shop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: ShopManagement/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shop.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }
            return View(shop);
        }

        // POST: ShopManagement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ShopName,ShopCreationDate,ShopLogoNetworkPath")] Shop shop)
        {
            if (id != shop.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopExists(shop.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: ShopManagement/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shop
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // POST: ShopManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shop = await _context.Shop.FindAsync(id);
            if (shop != null)
            {
                _context.Shop.Remove(shop);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShopExists(int id)
        {
            return _context.Shop.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_AppLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TSENA</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TSENA.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/img/logo/online-shopping.png" type="image/x-icon">
</head>
<body>
    <div class="container">

        <div class="sidebar">
            <nav>
                <ul class="navbar-nav flex-grow-1">
                    <li>
                        <a asp-area="" asp-controller="ShopManagement" asp-action="Index">
                            <img src="~/img/icon/store-alt.png" alt="Toutes les boutiques" title="Toutes les boutiques">
                        </a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Parametre">
                            <img src="~/img/icon/api.png" alt="Paramètre" title="Paramètre">
                        </a>
                    </li>
                    <!-- <li>
                        <a asp-area="" asp-controller="Product" asp-action="Index">
                            <img src="~/img/icon/api.png" alt="Paramètre" title="Paramètre">
                        </a>
                    </li> -->
                </ul>
            </nav>
        </div>

        

        <div class="right_side_bar">
            <nav>
                <ul>
                    <li class="logo">Tsena <img src="~/img/logo/online-shopping.png" alt=""></li>
                    <li>
                        <div class="profil">
                            <img src="~/img/profil/profil.JPG" alt="">
                        </div>
                    </li>                 
                </ul>
            </nav>
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    </div>
    

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_AuthenticationLayout.cshtml
@{
	Layout = "_Layout";
}

<header>
	<nav>
		<ul>
			<li class="logo">
				<a asp-action="Index" asp-controller="ShopManagement">
					Tsena <img src="~/img/logo/online-shopping.png" alt="">
				</a>
			</li>
			<li>
				<ul class="menu-elements">
					<li>
						<a asp-controller="ShopManagement" asp-action="Index">Accueil</a>
					</li>
					<li>
						<a asp-controller="Authentication" asp-action="Login">Connexion</a>
					</li>
					<li>
						<a asp-controller="Authentication" asp-action="Register">Inscription</a>
					</li>
				</ul>
				<section>
					<img src="~/img/menu.png"/>
				</section>
			</li>
		</ul>
	</nav>
</header>
<main>
	@RenderBody()
</main>

Views/Shared/_HomeLayout.cshtml
@{
    Layout = "_Layout";
}

<div class="container">
        <div class="sidebar">
            <nav>
                <ul class="navbar-nav flex-grow-1">
                    @* @if(User.Identity?.IsAuthenticated ?? false){ *@
                        <li>
                            <a asp-area="" asp-controller="ShopManagement" asp-action="Index">
                                <img src="~/img/icon/store-alt.png" alt="Toutes les boutiques" title="Toutes les boutiques">
                            </a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="Chart">
                                <img src="~/img/cart.png" alt="Panier" title="Panier">
                            </a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Home" asp-action="Parametre">
                                <img src="~/img/icon/api.png" alt="Paramètre" title="Paramètres">
                            </a>
                        </li>
                    @* }else{
                        <li class="disabled-link">
                            <a asp-area="">
                                <img src="~/img/icon/store-alt.png" alt="Toutes les boutiques" title="Toutes les boutiques">
                            </a>
                        </li>
                        <li class="disabled-link">
                            <a asp-area="">
                                <img src="~/img/cart.png" alt="Panier" title="Panier">
                            </a>
                        </li>
                        <li class="disabled-link">
                            <a asp-area="">
                                <img src="~/img/icon/api.png" alt="Paramètre" title="Paramètres">
                            </a>
                        </li>
                    } *@
                </ul>
            </nav>
        </div>
        <div class="right_side_bar">
            <nav>
                <ul class="userinfo-container">
                    <li class="logo">
                        <a asp-action="Index" asp-controller="ShopManagement">
                            Tsena <img src="~/img/logo/online-shopping.png" alt="">
                        </a>
            	    </li>
                    @*
                        <li>
                            <div class="profil">
                                <img src="~/img/profil/profil.JPG" alt="">
                            </div>
                        </li>
                    *@
                    @if(User.Identity?.IsAuthenticated ?? false){
                        <li>
                            <form asp-action="Logout" asp-controller="Authentication">
                                <a>
                                    <button>Se déconnecter</button>
                                </a>
                            </form>
                        </li>
                    }else{
                        <li>
                            <a asp-controller="Authentication" asp-action="Login">
                                <button>Se connecter</button>
                            </a>
                        </li>
                    }
                </ul>
            </nav>
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="robots" content="index, follow" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TSENA</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Settings.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ChangePassword.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TSENA.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/img/logo/online-shopping.png" type="image/x-icon">
</head>
<body>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>